# Generated by Django 3.2.5 on 2022-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='/home/pulkit/dev19/django/musicwire/media\\default_album_cover.png', upload_to='album_logo/'),
        ),
    ]
